### ISSUE TITLE
Set Up of Basic React Project

### ISSUE THREAD

**Issue by fknmcapstone** [rebeccalashley/fknmdashboard#1]
- [x] Define a general file structure
- [x] Start up a basic website - can be as simple as just hello world

**Comment by fknmcapstone** [comment]
Sample file structure article: https://medium.com/@kthamodaran/react-8-best-practices-folder-structure-5dbda48a69e#:~:text=The%20most%20important%20advantage%20of,get%20listed%2C%20as%20shown%20below.

**Comment by Xyrtur** [comment]
Regarding file structure and architecture of our website:
- [MVC architecture](https://blog.javascripttoday.com/blog/model-view-controller-architecture/)
- [File structure](https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/) for specifically a Node.Js project using MVC
     - Specifically says though to not use `controllers`, `models`, and `views`. Rather separate differently
     - [This link](https://reintech.io/blog/structuring-a-nodejs-project-a-comprehensive-guide-for-software-developers) also does the same and separates according to "modules" which I like. It's like a variant of MVC
     - **Will be sticking to normal MVC unless the variant makes it that much more readable**
- [Another example file structure](https://www.scaler.com/topics/nodejs/node-js-project-structure/)
- Looks like most articles I see on organizing a Node.Js project assume an MVC architecture is being used
- [Node.Js best practices article for project architecture](https://blog.logrocket.com/node-js-project-architecture-best-practices/)

Seems like our file structure might look something like this:
├── config/                                    # Configuration files
    ├─ utils/                                        # Middleware files, I think the name utils makes more sense for helper functions
    ├─ services/                                 # Might not need this
    ├─ node_modules/                              
    ├─ controllers/
    ├─ models/
    ├─ views/
    ├─ other files
    ├─ license file
    ├─ package.json
    └─ .gitignore

**Comment by Xyrtur** [comment]
Updated the repo with a basic file structure as well an index.js file showing a basic "Hello World" site. Will now be working on creating a page with a basic layout, the first task in [this Landing Page issue](https://github.com/fknmcapstone/fknmdashboard/issues/2#issue-1969295227).
